2018-04-19 03:57:18,855 - pystorm.component.normalize - INFO - - [pid=20605] - Processing received message [***The]
2018-04-19 03:57:18,855 - pystorm.component.normalize - ERROR - Exception in NormalizerBolt.run()
Traceback (most recent call last):
  File "/data/virtualenvs/TopWordFinderTopologyPartD/local/lib/python2.7/site-packages/pystorm/component.py", line 488, in run
    self._run()
  File "/data/virtualenvs/TopWordFinderTopologyPartD/local/lib/python2.7/site-packages/pystorm/bolt.py", line 197, in _run
    self.process(tup)
  File "/usr/local/apache-storm-1.0.6/storm-local/supervisor/stormdist/TopWordFinderTopologyPartD-20-1524110209/resources/bolts/NormalizerBolt.py", line 27, in process
    if word not in stopwords:
NameError: global name 'stopwords' is not defined
